.PHONY: clean All

All:
	@echo "----------Building project:[ Practica - Debug ]----------"
	@cd "Practica" && "$(MAKE)" -f  "Practica.mk"
clean:
	@echo "----------Cleaning project:[ Practica - Debug ]----------"
	@cd "Practica" && "$(MAKE)" -f  "Practica.mk" clean
